### ISSUE TITLE
Seq diagram of change queue in DD

### ISSUE THREAD

**Issue by carduz** [sweng2/sweng2#78]
it was required during the presentations

**Comment by gdejaege** [comment]
I think we do not have exactly the same thing that the one explained during the presentations.

In the other applications they have the application itself sending taxis to different queues to balance them correctly and not have empty queues. For this part there is the need to explain how it works.

In our application, we do not have that (I do not remember we talking about it, but in the scenarios it is written that if a taxi queue is to long, the taxi driver himself will change queue because he does not want to wait to long)

So what should we do ?

**Comment by carduz** [comment]
I think that we should write these reasons and conclusions in 'other design' decisions

**Comment by gdejaege** [comment]
I think our solution is not so good, because the taxi drivers should at least be able to visualise the different waiting queues, it's shouldn't be necessary to go in a specific zone to check it's waiting queue. It's time and fuel loss

**Comment by tux-mind** [comment]
scheduled in a67d67bc6d
